security:
  oauth2:
    client:
      clientId: 230472117326688
      clientSecret: c42847e0d9dd81f33d8fe639628b8f77
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
    resource:
      userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: RELEASE

spring:
  resources:
    chain:
      enabled: true
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: test

server:
  port: 7777

